### ISSUE TITLE
NoSuchElementException Thrown in LayoutContext

### ISSUE THREAD

**Issue by jnmlinden** [flyingsaucerproject/flyingsaucer#429]
After the upgrade from v9.9.5 to v9.10.0, an exception is occasionally thrown in LayoutContext.getBlockFormattingContext(), when the Deque field is empty. What could cause this to happen?

![grafik](https://github.com/user-attachments/assets/790b8f05-a03a-41e7-9a82-ea2701dfa754)

**Comment by asolntsev** [comment]
@jnmlinden please share the full error message with stacktrace.
Ideally, share a java sample+html to reproduce the problem.

**Comment by TimoFrye** [comment]
Got the same Error:

java.util.NoSuchElementException: null
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
	at org.xhtmlrenderer.layout.LayoutContext.getBlockFormattingContext(LayoutContext.java:206)
	at org.xhtmlrenderer.layout.LayoutUtil.layoutFloated(LayoutUtil.java:85)
	at org.xhtmlrenderer.layout.InlineBoxing.processOutOfFlowContent(InlineBoxing.java:863)
	at org.xhtmlrenderer.layout.InlineBoxing.layoutContent(InlineBoxing.java:313)
	at org.xhtmlrenderer.render.BlockBox.layoutInlineChildren(BlockBox.java:1003)
	at org.xhtmlrenderer.render.AnonymousBlockBox.layout(AnonymousBlockBox.java:55)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutBlockChild0(BlockBoxing.java:318)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutBlockChild(BlockBoxing.java:296)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutContent(BlockBoxing.java:89)
	at org.xhtmlrenderer.render.BlockBox.layoutChildren(BlockBox.java:987)
	at org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:867)
	at org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:796)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutBlockChild0(BlockBoxing.java:318)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutBlockChild(BlockBoxing.java:296)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutContent(BlockBoxing.java:89)
	at org.xhtmlrenderer.render.BlockBox.layoutChildren(BlockBox.java:987)
	at org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:867)
	at org.xhtmlrenderer.newtable.TableRowBox.layoutCell(TableRowBox.java:460)
	at org.xhtmlrenderer.newtable.TableRowBox.layoutChildren(TableRowBox.java:213)
	at org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:867)
	at org.xhtmlrenderer.newtable.TableRowBox.layout(TableRowBox.java:96)
	at org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:796)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutBlockChild0(BlockBoxing.java:318)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutBlockChild(BlockBoxing.java:296)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutContent(BlockBoxing.java:89)
	at org.xhtmlrenderer.render.BlockBox.layoutChildren(BlockBox.java:987)
	at org.xhtmlrenderer.newtable.TableSectionBox.layoutChildren(TableSectionBox.java:140)
	at org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:867)
	at org.xhtmlrenderer.newtable.TableSectionBox.layout(TableSectionBox.java:281)
	at org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:796)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutBlockChild0(BlockBoxing.java:318)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutBlockChild(BlockBoxing.java:296)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutContent(BlockBoxing.java:89)
	at org.xhtmlrenderer.render.BlockBox.layoutChildren(BlockBox.java:987)
	at org.xhtmlrenderer.newtable.TableBox.layoutChildren(TableBox.java:326)
	at org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:867)
	at org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:796)
	at org.xhtmlrenderer.newtable.TableBox.layoutTable(TableBox.java:291)
	at org.xhtmlrenderer.newtable.TableBox.layout(TableBox.java:250)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutBlockChild0(BlockBoxing.java:318)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutBlockChild(BlockBoxing.java:296)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutContent(BlockBoxing.java:89)
	at org.xhtmlrenderer.render.BlockBox.layoutChildren(BlockBox.java:987)
	at org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:867)
	at org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:796)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutBlockChild0(BlockBoxing.java:318)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutBlockChild(BlockBoxing.java:296)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutContent(BlockBoxing.java:89)
	at org.xhtmlrenderer.render.BlockBox.layoutChildren(BlockBox.java:987)
	at org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:867)
	at org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:796)
	at org.xhtmlrenderer.pdf.ITextRenderer.layout(ITextRenderer.java:275)

**Comment by paultbeck** [comment]
I'm seeing the same issue upgrading from v9.9.5 to v9.10.1. 

Stack trace:
```java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
	at org.xhtmlrenderer.layout.LayoutContext.getBlockFormattingContext(LayoutContext.java:206)
	at org.xhtmlrenderer.layout.LayoutContext.translate(LayoutContext.java:253)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutBlockChild0(BlockBoxing.java:319)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutBlockChild(BlockBoxing.java:296)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutContent(BlockBoxing.java:89)
	at org.xhtmlrenderer.render.BlockBox.layoutChildren(BlockBox.java:987)
	at org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:867)
	at org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:796)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutBlockChild0(BlockBoxing.java:318)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutBlockChild(BlockBoxing.java:296)
	at org.xhtmlrenderer.layout.BlockBoxing.layoutContent(BlockBoxing.java:89)
	at org.xhtmlrenderer.render.BlockBox.layoutChildren(BlockBox.java:987)
	at org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:867)
	at org.xhtmlrenderer.render.BlockBox.layout(BlockBox.java:796)
	at org.xhtmlrenderer.pdf.ITextRenderer.layout(ITextRenderer.java:275)

**Comment by thced** [comment]
Same issue here.

**Comment by asolntsev** [comment]
@jnmlinden @TimoFrye @paultbeck @thced Please share a html sample to reproduce the problem.

**Comment by pinguedwinde** [comment]
Thanks @asolntsev
